In [5]:
import torch
from torch import nn

In [3]:
linear = nn.Linear(32, 2)  # 输入32维，输出2维

In [6]:
inputs = torch.rand(3, 32)  # 创建一个形状为（3， 32）的随机张量，3为批次大小

In [7]:
outputs = linear(inputs)  # 输出张量形状为（3， 2）

In [8]:
outputs

tensor([[-0.5265, -0.2535],
        [-0.2804, -0.1383],
        [-0.4712,  0.1166]], grad_fn=<AddmmBackward0>)

### sigmoid、softmax等激活函数包含在torch.nn.functional中

In [9]:
from torch.nn import functional as F
activation = F.sigmoid(outputs)
activation

tensor([[0.3713, 0.4370],
        [0.4304, 0.4655],
        [0.3843, 0.5291]], grad_fn=<SigmoidBackward0>)

In [10]:
activation = F.softmax(outputs, dim=1)  # dim=1，对每个批次中的各样例分别进行softmax运算
activation

tensor([[0.4322, 0.5678],
        [0.4645, 0.5355],
        [0.3571, 0.6429]], grad_fn=<SoftmaxBackward0>)

In [11]:
activation = F.relu(outputs)
activation

tensor([[0.0000, 0.0000],
        [0.0000, 0.0000],
        [0.0000, 0.1166]], grad_fn=<ReluBackward0>)