In [1]:
import torch

In [2]:
from torch.nn import Conv1d

## 卷积层

In [27]:
conv1 = Conv1d(5, 2, 4)  # 参数分别为输入通道大小，输出通道大小，卷积核宽度

In [34]:
conv2 = Conv1d(5, 2, 3)

In [35]:
inputs = torch.rand(2, 5, 6)

In [36]:
outputs1 = conv1(inputs)

In [37]:
outputs2 = conv2(inputs)

In [38]:
outputs1

tensor([[[-0.0016, -0.1338,  0.4106],
         [ 0.2425,  0.4985,  0.2308]],

        [[-0.0020,  0.0319, -0.0123],
         [ 0.4043,  0.1047,  0.2210]]], grad_fn=<ConvolutionBackward0>)

In [39]:
outputs2

tensor([[[ 0.6053,  0.2567,  0.7348,  0.4860],
         [-0.1166, -0.0200, -0.0117, -0.0492]],

        [[ 0.7006,  0.4444,  0.2273,  0.4613],
         [-0.1450, -0.3334, -0.5307, -0.2686]]],
       grad_fn=<ConvolutionBackward0>)

## 池化层

In [40]:
from torch.nn import MaxPool1d

In [41]:
pool1 = MaxPool1d(3)  # 池化层核大小，即卷积层的输出序列长度

In [42]:
pool2 = MaxPool1d(4)

In [43]:
outputs_pool1 = pool1(outputs1)

In [44]:
outputs_pool2 = pool2(outputs2)

In [45]:
outputs_pool1

tensor([[[0.4106],
         [0.4985]],

        [[0.0319],
         [0.4043]]], grad_fn=<SqueezeBackward1>)

In [46]:
outputs_pool2

tensor([[[ 0.7348],
         [-0.0117]],

        [[ 0.7006],
         [-0.1450]]], grad_fn=<SqueezeBackward1>)

## 池化层函数

In [47]:
import torch.nn.functional as F

In [48]:
outputs_pool1 = F.max_pool1d(outputs1, kernel_size=outputs1.shape[2])

In [49]:
outputs_pool1

tensor([[[0.4106],
         [0.4985]],

        [[0.0319],
         [0.4043]]], grad_fn=<SqueezeBackward1>)

In [50]:
outputs_pool2 = F.max_pool1d(outputs2, kernel_size=outputs2.shape[2])

In [51]:
outputs_pool2

tensor([[[ 0.7348],
         [-0.0117]],

        [[ 0.7006],
         [-0.1450]]], grad_fn=<SqueezeBackward1>)

In [54]:
# 2*2*1变为2*2
outputs_pool_squeeze1 = outputs_pool1.squeeze(dim=2)

In [55]:
outputs_pool_squeeze1

tensor([[0.4106, 0.4985],
        [0.0319, 0.4043]], grad_fn=<SqueezeBackward1>)

In [56]:
outputs_pool_squeeze2 = outputs_pool2.squeeze(dim=2)

In [57]:
outputs_pool_squeeze2

tensor([[ 0.7348, -0.0117],
        [ 0.7006, -0.1450]], grad_fn=<SqueezeBackward1>)

In [58]:
# 拼接
outputs_pool = torch.cat([outputs_pool_squeeze1, outputs_pool_squeeze2], dim=1)

In [59]:
outputs_pool

tensor([[ 0.4106,  0.4985,  0.7348, -0.0117],
        [ 0.0319,  0.4043,  0.7006, -0.1450]], grad_fn=<CatBackward0>)

### 池化后连接一个全连接层，实现分类功能

In [60]:
from torch.nn import Linear

In [61]:
linear = Linear(4, 2)

In [62]:
outputs_linear = linear(outputs_pool)

In [63]:
outputs_linear

tensor([[0.0039, 1.0501],
        [0.1493, 0.8199]], grad_fn=<AddmmBackward0>)