In [1]:
import torch
from torch.nn import LSTM

In [2]:
lstm = LSTM(input_size=4, hidden_size=5, batch_first=True)

In [3]:
inputs = torch.rand(2, 3, 4)

In [5]:
outputs, (hn, cn) = lstm(inputs)  # cn最后一个时刻的记忆细胞

In [6]:
outputs

tensor([[[-0.0871, -0.0022, -0.1024, -0.1055, -0.0509],
         [-0.1377,  0.0495, -0.1342, -0.1802, -0.1329],
         [-0.0961,  0.1128, -0.1886, -0.2101, -0.0271]],

        [[-0.1080, -0.0635, -0.0588, -0.1105, -0.0700],
         [-0.0955,  0.0191, -0.1242, -0.1610, -0.0839],
         [-0.0887,  0.1168, -0.1838, -0.1895, -0.0822]]],
       grad_fn=<TransposeBackward0>)

In [7]:
hn

tensor([[[-0.0961,  0.1128, -0.1886, -0.2101, -0.0271],
         [-0.0887,  0.1168, -0.1838, -0.1895, -0.0822]]],
       grad_fn=<StackBackward0>)

In [8]:
cn

tensor([[[-0.2499,  0.1841, -0.3756, -0.4434, -0.0516],
         [-0.2295,  0.1799, -0.3366, -0.3996, -0.1717]]],
       grad_fn=<StackBackward0>)

In [9]:
outputs.shape

torch.Size([2, 3, 5])

In [10]:
hn.shape

torch.Size([1, 2, 5])

In [11]:
cn.shape

torch.Size([1, 2, 5])