# Transformer

## transformer块(编码器块)

In [4]:
import torch
from torch import nn

In [5]:
encoder_layer = nn.TransformerEncoderLayer(d_model=4, nhead=2)  # d_model输入向量维度

In [15]:
src = torch.rand(2, 3, 4)  # 参数分别为序列长度，批次大小，每个输入向量的维度

In [7]:
out = encoder_layer(src)

In [10]:
out

tensor([[[ 1.6171, -0.5061, -1.0613, -0.0497],
         [ 1.1192,  0.7702, -1.3743, -0.5151],
         [-0.0191, -1.0781,  1.6058, -0.5087]],

        [[ 1.2430, -0.1356, -1.5085,  0.4011],
         [ 0.4580, -0.6016, -1.2355,  1.3791],
         [ 1.3115, -0.2022, -1.4557,  0.3464]]],
       grad_fn=<NativeLayerNormBackward0>)

## 多个transformer块（编码器）

In [11]:
transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=6)

In [12]:
out = transformer_encoder(src)

In [13]:
out

tensor([[[ 1.2377,  0.5348, -1.4390, -0.3335],
         [-0.4102,  1.5145,  0.1291, -1.2334],
         [ 0.0787,  0.9051,  0.6680, -1.6518]],

        [[ 1.5663,  0.1434, -1.0345, -0.6752],
         [ 0.9824, -0.5532, -1.3628,  0.9336],
         [ 1.5018,  0.3119, -0.9411, -0.8727]]],
       grad_fn=<NativeLayerNormBackward0>)

### 解码器

In [14]:
memory = transformer_encoder(src)

In [16]:
decoder_layer = nn.TransformerDecoderLayer(d_model=4, nhead=2)

In [18]:
transformer_decoder = nn.TransformerDecoder(decoder_layer, num_layers=6)

In [19]:
tgt = torch.rand(2, 3, 4)

In [20]:
out = transformer_decoder(tgt, memory)  # tgt为解码器的输入，memory为编码器学习得到

In [21]:
out

tensor([[[-0.4753,  0.0035,  1.5892, -1.1174],
         [-1.2090,  0.2629, -0.5322,  1.4784],
         [-0.7810, -0.5426,  1.7153, -0.3917]],

        [[ 1.2651, -1.1545, -0.7835,  0.6728],
         [-1.3713,  0.7533, -0.5160,  1.1339],
         [-0.2022, -1.1544,  1.6020, -0.2453]]],
       grad_fn=<NativeLayerNormBackward0>)