# 数据中不同句子的长度不同，先将一个批次的句子拼接，再记录每个句子开始的位置

In [15]:
import torch
from torch import nn

In [2]:
input1 = torch.tensor([0, 1, 2, 1], dtype=torch.long)

In [3]:
input2 = torch.tensor([2, 1, 3, 7, 5], dtype=torch.long)

In [4]:
input3 = torch.tensor([6, 4, 2], dtype=torch.long)

In [5]:
input4 = torch.tensor([1, 3, 4, 3, 5, 7], dtype=torch.long)

In [6]:
inputs = [input1, input2, input3, input4]

In [7]:
inputs

[tensor([0, 1, 2, 1]),
 tensor([2, 1, 3, 7, 5]),
 tensor([6, 4, 2]),
 tensor([1, 3, 4, 3, 5, 7])]

In [8]:
offsets = [0] + [i.shape[0] for i in inputs]

In [9]:
offsets

[0, 4, 5, 3, 6]

In [10]:
offsets = torch.tensor(offsets[:-1]).cumsum(dim=0)  # cumsum沿着某方向上的累加

In [11]:
offsets

tensor([ 0,  4,  9, 12])

In [12]:
inputs = torch.cat(inputs)

In [13]:
inputs

tensor([0, 1, 2, 1, 2, 1, 3, 7, 5, 6, 4, 2, 1, 3, 4, 3, 5, 7])

In [16]:
embeddingbag = nn.EmbeddingBag(num_embeddings=8, embedding_dim=3)

In [17]:
embeddings = embeddingbag(inputs, offsets)

In [18]:
embeddings

tensor([[ 0.6599,  0.2838, -0.4600],
        [ 0.2742,  0.6886, -0.4493],
        [ 0.3077,  0.3370, -0.1834],
        [ 0.3323,  0.2237, -0.3745]], grad_fn=<EmbeddingBagBackward0>)